package com.kuang.pojo;

import lombok.Data;

@Data
public class DocRate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_rate.id
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_rate.phone
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_rate.d_name
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    private String dName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_rate.rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    private String rate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doc_rate.score
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    private Float score;


}