package com.kuang.pojo;


import lombok.Data;

import java.util.Date;
@Data
public class EldInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.id
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.e_name
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.temperature
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Double temperature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.pulse
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Integer pulse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.breathe
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Integer breathe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.blood_pre
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Integer bloodPre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.weight
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.blood_sugar
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Double bloodSugar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.sleep
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Double sleep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.med_history
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private String medHistory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.mental_status
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private String mentalStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.time
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.res_doctor
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private String resDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.doc_propose
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private String docPropose;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_info.online
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    private Integer online;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.id
     *
     * @return the value of eld_info.id
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.id
     *
     * @param id the value for eld_info.id
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.e_name
     *
     * @return the value of eld_info.e_name
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public String geteName() {
        return eName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.e_name
     *
     * @param eName the value for eld_info.e_name
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void seteName(String eName) {
        this.eName = eName == null ? null : eName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.temperature
     *
     * @return the value of eld_info.temperature
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Double getTemperature() {
        return temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.temperature
     *
     * @param temperature the value for eld_info.temperature
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setTemperature(Double temperature) {
        this.temperature = temperature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.pulse
     *
     * @return the value of eld_info.pulse
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Integer getPulse() {
        return pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.pulse
     *
     * @param pulse the value for eld_info.pulse
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setPulse(Integer pulse) {
        this.pulse = pulse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.breathe
     *
     * @return the value of eld_info.breathe
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Integer getBreathe() {
        return breathe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.breathe
     *
     * @param breathe the value for eld_info.breathe
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setBreathe(Integer breathe) {
        this.breathe = breathe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.blood_pre
     *
     * @return the value of eld_info.blood_pre
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Integer getBloodPre() {
        return bloodPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.blood_pre
     *
     * @param bloodPre the value for eld_info.blood_pre
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setBloodPre(Integer bloodPre) {
        this.bloodPre = bloodPre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.weight
     *
     * @return the value of eld_info.weight
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.weight
     *
     * @param weight the value for eld_info.weight
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.blood_sugar
     *
     * @return the value of eld_info.blood_sugar
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Double getBloodSugar() {
        return bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.blood_sugar
     *
     * @param bloodSugar the value for eld_info.blood_sugar
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setBloodSugar(Double bloodSugar) {
        this.bloodSugar = bloodSugar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.sleep
     *
     * @return the value of eld_info.sleep
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Double getSleep() {
        return sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.sleep
     *
     * @param sleep the value for eld_info.sleep
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setSleep(Double sleep) {
        this.sleep = sleep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.med_history
     *
     * @return the value of eld_info.med_history
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public String getMedHistory() {
        return medHistory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.med_history
     *
     * @param medHistory the value for eld_info.med_history
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setMedHistory(String medHistory) {
        this.medHistory = medHistory == null ? null : medHistory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.mental_status
     *
     * @return the value of eld_info.mental_status
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public String getMentalStatus() {
        return mentalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.mental_status
     *
     * @param mentalStatus the value for eld_info.mental_status
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setMentalStatus(String mentalStatus) {
        this.mentalStatus = mentalStatus == null ? null : mentalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.time
     *
     * @return the value of eld_info.time
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.time
     *
     * @param time the value for eld_info.time
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.res_doctor
     *
     * @return the value of eld_info.res_doctor
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public String getResDoctor() {
        return resDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.res_doctor
     *
     * @param resDoctor the value for eld_info.res_doctor
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setResDoctor(String resDoctor) {
        this.resDoctor = resDoctor == null ? null : resDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.doc_propose
     *
     * @return the value of eld_info.doc_propose
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public String getDocPropose() {
        return docPropose;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.doc_propose
     *
     * @param docPropose the value for eld_info.doc_propose
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setDocPropose(String docPropose) {
        this.docPropose = docPropose == null ? null : docPropose.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column eld_info.online
     *
     * @return the value of eld_info.online
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public Integer getOnline() {
        return online;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column eld_info.online
     *
     * @param online the value for eld_info.online
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    public void setOnline(Integer online) {
        this.online = online;
    }
}