package com.kuang.pojo;

import lombok.Data;

@Data
public class EldStatus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.id
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.e_name
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private String eName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.password
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.e_sex
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private String eSex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.e_age
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private Integer eAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.phone
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eld_status.address
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    private String address;




}