package com.kuang.dao;


import com.kuang.dto.DocRateDTO;
import com.kuang.pojo.DocRate;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;
@Mapper
public interface DocRateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int countByExample(DocRate example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int deleteByExample(DocRate example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int insert(DocRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int insertSelective(DocRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    List<DocRate> selectByExample(DocRate example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    List<DocRate> selectByPrimaryKey(Long id);

    List<DocRateDTO> selectAllSc();
    List<DocRate> selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int updateByExampleSelective(@Param("record") DocRate record, @Param("example") DocRate example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int updateByExample(@Param("record") DocRate record, @Param("example") DocRate example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int updateByPrimaryKeySelective(DocRate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table doc_rate
     *
     * @mbggenerated Thu Apr 20 13:12:31 CST 2023
     */
    int updateByPrimaryKey(DocRate record);

}