package com.kuang.dao;


import com.kuang.dto.EldFenYeDto;
import com.kuang.pojo.EldInfo;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.data.domain.Pageable;

import java.util.List;
@Mapper
public interface EldInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int countByExample(EldInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int deleteByExample(EldInfo example);

    EldInfo selectById(Long id);

    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int insert(EldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int insertSelective(EldInfo record);

    long SelectCount();
    List<EldInfo> selectByExample(EldInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    List<String> selectByDoc(String res_doctor);

    List<EldInfo>  selectALL(String res_doctor,Pageable pageable);

    List<EldInfo> selectByName(String name);

    //管理员的信息展示
    List<EldInfo> selectALLInfo(Pageable pageable);
    List<EldInfo> selectALLByFenYeInfo(Integer pageNo,Integer pageSize);

    String selectByPhone(String name);

    List<EldInfo> selectALLByFenYe(EldFenYeDto eldFenYeDto);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int updateByExampleSelective(@Param("record") EldInfo record, @Param("example") EldInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int updateByExample(@Param("record") EldInfo record, @Param("example") EldInfo example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int updateByPrimaryKeySelective(EldInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_info
     *
     * @mbggenerated Fri Mar 31 23:07:01 CST 2023
     */
    int updateByPrimaryKey(EldInfo record);
    int updateProByName(String eName,String docPropose);
}