package com.kuang.dao;

import com.kuang.pojo.EldStatus;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

import java.util.List;
@Mapper
@Repository
public interface EldStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int countByExample(EldStatus example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int deleteByExample(EldStatus example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int insert(EldStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int insertSelective(EldStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    List<EldStatus> selectByExample(EldStatus example);

    /**
     * 查询用户账号和密码
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    EldStatus selectByPrimaryKey(String phone,String password);

    List<EldStatus> selectByNames(List<String> name);
    String selectByPhone(String phone);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int updateByExampleSelective(@Param("record") EldStatus record, @Param("example") EldStatus example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int updateByExample(@Param("record") EldStatus record, @Param("example") EldStatus example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int updateByPrimaryKeySelective(EldStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table eld_status
     *
     * @mbggenerated Sat Mar 25 16:15:30 CST 2023
     */
    int updateByPrimaryKey(EldStatus record);
}